# Generated by Django 3.0.3 on 2021-04-22 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_uiproject'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intro', models.CharField(max_length=400)),
                ('about', models.CharField(max_length=400)),
                ('image', models.ImageField(upload_to='Profile/')),
            ],
        ),
    ]
