# Generated by Django 3.0.3 on 2021-04-22 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_personaldata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personaldata',
            name='about',
            field=models.TextField(),
        ),
    ]
