# Generated by Django 3.0.3 on 2021-04-22 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_assets'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assets',
            name='cv',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='assets',
            name='favicon',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='assets',
            name='logo',
            field=models.CharField(max_length=1000),
        ),
    ]
