# Generated by Django 3.0.3 on 2021-04-23 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0007_auto_20210422_1746'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UseCase',
            new_name='UserCase',
        ),
        migrations.AddField(
            model_name='uiproject',
            name='description',
            field=models.CharField(default='N/A', max_length=400),
        ),
        migrations.AddField(
            model_name='uiproject',
            name='title',
            field=models.CharField(default='N/A', max_length=100),
        ),
    ]
